### ISSUE TITLE
Querying is broken

### ISSUE THREAD

**Issue by borod108** [ManageIQ/ovirt_metrics#24]
2.4.1 :006 > OvirtMetrics::VmSamplesHistory.where(vm_id: '1111')
OvirtLegacyPostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0
Could not log "sql.active_record" event. TypeError: wrong argument type String (must respond to :each) ["/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/log_subscriber.rb:37:in zip'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/log_subscriber.rb:37:insql'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/subscriber.rb:95:in finish'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/log_subscriber.rb:83:infinish'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/fanout.rb:102:in finish'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/fanout.rb:46:inblock in finish'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/fanout.rb:46:in each'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/fanout.rb:46:infinish'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:42:in finish_with_state'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:27:ininstrument'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:583:in log'", "/home/bod108/git/ovirt_metrics/lib/active_record/connection_adapters/ovirt_legacy_postgresql_adapter.rb:618:inexec_cache'", "/home/bod108/git/ovirt_metrics/lib/active_record/connection_adapters/ovirt_legacy_postgresql_adapter.rb:602:in execute_and_clear'", "/home/bod108/git/ovirt_metrics/lib/active_record/connection_adapters/ovirt_legacy_postgresql/database_statements.rb:103:inexec_query'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in select_prepared'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:39:inselect_all'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in select_all'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/querying.rb:39:infind_by_sql'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/relation.rb:706:in exec_queries'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/relation.rb:583:inload'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/relation.rb:260:in records'", "/home/bod108/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/relation.rb:686:ininspect'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/inspector.rb:109:in block in <module:IRB>'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/inspector.rb:102:ininspect_value'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/context.rb:385:in inspect_last_value'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:665:inoutput_value'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:494:in block (2 levels) in eval_input'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:627:insignal_status'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb.rb:490:in block in eval_input'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:246:inblock (2 levels) in each_top_level_statement'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in loop'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:inblock in each_top_level_statement'", "/home/bod108/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'", "/home/bod108/.rvm/rubies/

**Comment by Fryguy** [comment]
cc @chrisarcand

**Comment by agrare** [comment]
@borod108 is this broken on gaprindashvili?

**Comment by borod108** [comment]
@chrisarcand did you get a chance to look at this?

**Comment by chrisarcand** [comment]
@borod108 No; if this *is* a bug on ManageIQ Gaprindashvili can you please create a BZ to be triaged appropriately?

**Comment by Ladas** [comment]
So the exceptions fails to log the query, if this is the error Jerome is seeing:


[----] E, [2017-12-04T13:38:42.634096 #20968:d3f130] ERROR -- : MIQ(ManageIQ::Providers::Redhat::InfraManager::MetricsCapture#perf_collect_metrics) [hourly] for: [ManageIQ::Providers::Redhat::InfraManager::Vm], [1227], [demo-insights-rhel70] Unhandled exception during perf data collection: [PG::InsufficientPrivilege: ERROR:  permission denied for relation vm_device_history
: SELECT DISTINCT device_id FROM "vm_device_history" WHERE "vm_device_history"."vm_id" = $1 AND "vm_device_history"."type" = $2 AND "vm_device_history"."delete_date" IS NULL], class: [ActiveRecord::StatementInvalid]
[----] E, [2017-12-04T13:38:42.634313 #20968:d3f130] ERROR -- : MIQ(ManageIQ::Providers::Redhat::InfraManager::MetricsCapture#perf_collect_metrics) [hourly] for: [ManageIQ::Providers::Redhat::InfraManager::Vm], [1227], [demo-insights-rhel70]   Timings at time of error: {:capture_state=>1.1297509670257568, :rhevm_connect=>0.04215526580810547, :collect_data=>0.020428895950317383}
[----] E, [2017-12-04T13:38:42.634528 #20968:d3f130] ERROR -- : [ActiveRecord::StatementInvalid]: PG::InsufficientPrivilege: ERROR:  permission denied for relation vm_device_history


------------
[PG::InsufficientPrivilege: ERROR:  permission denied for relation vm_device_history

It seems to be just wrongly configured database
-----

@borod108 can you fetch the actual exceptions from the DB, if this is the same issue? 

``` ActiveRecord::Base.logger = Logger.new(STDOUT)``` in rails c, could help to print the query

**Comment by borod108** [comment]
@Ladas after doing ActiveRecord::Base.logger = Logger.new(STDOUT) and redoing the query I got the same output.
Please note that if I comment out a few lines around ~/.rvm/gems/ruby-2.4.1/gems/activerecord-5.0.6/lib/active_record/log_subscriber.rb:37
I get no exception, it does not seem to me that there is an error thrown from the db.

**Comment by Ladas** [comment]
@borod108 I am pretty sure it's DB based error because of this line ```Could not log "sql.active_record" event. TypeError: wrong argument type String (must respond to :each) ```

So what we are seeing is error when trying to log DB based error. So we need to see what the actual error is.

**Comment by Ladas** [comment]
@borod108 also can you try ```OvirtMetrics::VmSamplesHistory.where(vm_id: 1111)```, the foreign key should be integer. (I am pretty sure rails can deal with that though)

**Comment by borod108** [comment]
@Ladas hi, it yields exactly the same result.

**Comment by chessbyte** [comment]
Addressed in https://github.com/ManageIQ/ovirt_metrics/pull/26
